#!/usr/bin/env python
# encoding: utf-8

"""
-------------------------------------------------
   File Name：     run_uitest
   Description :
   Author :        Meiyo
   date：          2018/3/20 17:28
-------------------------------------------------
   Change Activity:
                   2018/3/20:
------------------------------------------------- 
"""
__author__ = 'Meiyo'

import unittest
from testcases import test_caibao4_merchant
from testcases import test_caibao4_shopmanager
from testcases import test_caibao4_shopcashier
from testcases import test_caibao4_merchant_notVip
from HTMLTestRunner import HTMLTestRunner


if __name__ == '__main__':

    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_caibao4_merchant.MerchantActivateAndLogin))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_caibao4_shopmanager.ShopManagerLogin))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_caibao4_shopcashier.ShopCashierLogin))
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(
        test_caibao4_merchant_notVip.MerchantActivateAndLoginNotVip))

    with open('HTMLReport.html', 'w', encoding='utf-8') as f:
        runner = HTMLTestRunner(stream=f,
                                title='Caibao APP 4.0 UI Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2,
                                retry=2,
                                save_last_try=True
                                )
        runner.run(suite)







