#-------------------------------------------------
#   File Name：     config.yml
#   Description :
#   Author :        Meiyo
#   date：          2018/3/19 20:33
#-------------------------------------------------
#   Change Activity:
#                   2018/3/19:
#------------------------------------------------- 

MerchantInfo:
    merchant_code: A00300100000178
    password: 123456

ShopManagerInfo:
    usercode: 001
    password: a123456

CashierInfo:
    usercode: QingYu
    password: a123456



