#-------------------------------------------------
#   File Name：     config.yml
#   Description :
#   Author :        Meiyo
#   date：          2018/3/19 20:33
#-------------------------------------------------
#   Change Activity:
#                   2018/3/19:
#------------------------------------------------- 

MerchantInfo:
    merchant_code: A00300100000125
    password: a123456

ShopManagerInfo:
    usercode: qing
    password: a123456

CashierInfo:
    usercode: yu
    password: a123456



