#-------------------------------------------------
#   File Name：     config.yml
#   Description :
#   Author :        Meiyo
#   date：          2018/3/19 20:33
#-------------------------------------------------
#   Change Activity:
#                   2018/3/19:
#------------------------------------------------- 

MerchantInfo:
    merchant_code: A00305930000003
    password: a123456

ShopManagerInfo:
    usercode: Qing
    password: a123456

CashierInfo:
    usercode: Yu
    password: a123456



