#-------------------------------------------------
#   File Name：     config.yml
#   Description :
#   Author :        Meiyo
#   date：          2018/3/19 20:33
#-------------------------------------------------
#   Change Activity:
#                   2018/3/19:
#------------------------------------------------- 

MerchantInfo:
    merchant_code: 
    password: 

ShopManagerInfo:
    usercode: 
    password: 

CashierInfo:
    usercode: 
    password: 



